wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710737094.394018
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 15
      - 23
      4: 3.8.16
      5: 0.15.3
      8:
      - 5
