wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710736419.860699
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 17
      - 23
      4: 3.8.16
      5: 0.15.3
      8:
      - 5
